# Start Apache Beam Spark
# singularity run --pwd /opt/apache/beam docker://apache/beam_spark_job_server:latest


# Start Graphworld
singularity exec -B ${PWD}/src:/app,${PWD}/out:/app/out graphworld.sif python3 /app/beam_benchmark_main.py \
    --gin_files /app/configs/SSL_nodeclassification/mwe/nodeclassification_mwe_jl.gin \
    --runner DirectRunner \
    --output /app/out/non_working_singularity \
    --job_endpoint localhost:8098

# Kill the Apache Beam Spark
# kill -9 `lsof -t -i:8098`
