@echo off
rem ########## Generated by ChatGPT ##########
rem Copyright 2022 Google LLC
rem
rem Licensed under the Apache License, Version 2.0 (the "License");
rem you may not use this file except in compliance with the License.
rem You may obtain a copy of the License at
rem
rem      http://www.apache.org/licenses/LICENSE-2.0
rem
rem Unless required by applicable law or agreed to in writing, software
rem distributed under the License is distributed on an "AS IS" BASIS,
rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
rem See the License for the specific language governing permissions and
rem limitations under the License.

cd ..

set PROJECT_NAME=project
set BUILD_NAME=graphworld

set tag_name=%BUILD_NAME%:latest

docker build . -t %tag_name% -t gcr.io/%PROJECT_NAME%/%BUILD_NAME%:latest


rem Set the filename
echo Saving file...
set filename=./graphworld_image.tar
docker save %tag_name% -o %filename%
echo Saved file %filename%
